# Базовий образ
FROM ubuntu:latest

# Додати MailCow репозиторій
RUN git clone https://github.com/mailcow/mailcow-dockerized.git /mailcow-dockerized

# Змінити робочу директорію
WORKDIR /mailcow-dockerized

# Встановлення curl перед генерацією конфігурації
RUN apt update && apt install -y curl

# Генерація конфігурації
RUN ./generate_config.sh

# Запуск MailCow через docker-compose
CMD ["docker-compose", "up", "-d"]
