# Базовий образ
FROM ubuntu:latest

# Оновлення пакетів та встановлення необхідних інструментів
RUN apt update && apt install -y git curl

# Клонування MailCow
RUN git clone https://github.com/mailcow/mailcow-dockerized.git /mailcow-dockerized

# Зміна робочої директорії
WORKDIR /mailcow-dockerized

# Генерація конфігурації MailCow
RUN ./generate_config.sh

# Запуск MailCow за допомогою docker-compose
CMD ["docker-compose", "up", "-d"]
