services:
  - type: web
    name: mailcow
    env: docker
    plan: free
    buildCommand: |
      apt update
      apt install -y git docker.io docker-compose
      git clone https://github.com/mailcow/mailcow-dockerized.git
      cd mailcow-dockerized
      ./generate_config.sh
    startCommand: |
      cd mailcow-dockerized
      docker-compose up -d
